export const STATUS_LIST_REQUEST = "STATUS_LIST_REQUEST";
export const STATUS_LIST_SUCCESS = "STATUS_LIST_SUCCESS";
export const STATUS_LIST_FAIL = "STATUS_LIST_FAIL";

//is Details {id}
export const STATUS_DETAILS_REQUEST = "STATUS_DETAILS_REQUEST";
export const STATUS_DETAILS_SUCCESS = "STATUS_DETAILS_SUCCESS";
export const STATUS_DETAILS_FAIL = "STATUS_DETAILS_FAIL";
